[project]
name = "deplock"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [{ name = "Tyler Zupan", email = "tzupan@squareup.com" },
           { name = "Josh Hamet", email = "jhamet@squareup.com" },
]
requires-python = ">=3.10"
dependencies = [
    "poetry>=2.1.3",
    "pydantic>=2.11.7",
    "tomlkit>=0.13.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["deplock"]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true

[dependency-groups]
dev = [
    "ruff >=0.7.0, <1.0.0",
    "pytest >=6.2.5, <7.0.0",
    "ty>=0.0.1a9",
]

[tool.ruff]
# Pulled from here: https://docs.astral.sh/ruff/configuration/
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
ignore = ["F401"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"