contact_links:
    - name: ❓ Questions and Help 🤔
      url: https://discord.gg/block-opensource
      about: This issue tracker is not for support questions. Please refer to the community for more help.
